services:
  postgres-dev:
    image: 'postgres:14.15-alpine3.21'
    environment:
      - 'POSTGRES_DB=${DB_DEV}'
      - 'POSTGRES_PASSWORD=${PASSWORD_DB_DEV}'
      - 'POSTGRES_USER=${POSTGRES_USER_DEV}'
    ports:
      - '5433:5432'
    volumes:
      - postgres_dev_data2:/var/lib/postgresql/data
    profiles:
      - dev

  postgres-prod:
    image: 'postgres:14.15-alpine3.21'
    environment:
      - 'POSTGRES_DB=${DB_PROD}'
      - 'POSTGRES_PASSWORD=${PASSWORD_DB_PROD}'
      - 'POSTGRES_USER=${POSTGRES_USER_PROD}'
    ports:
      - '5434:5432'
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    profiles:
      - prod

  postgres-test:
    image: 'postgres:14.15-alpine3.21'
    environment:
      - 'POSTGRES_DB=${DB_TEST}'
      - 'POSTGRES_PASSWORD=${PASSWORD_DB_TEST}'
      - 'POSTGRES_USER=${POSTGRES_USER_TEST}'
    ports:
      - '5435:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    profiles:
      - test
volumes:
  postgres_dev_data2:
  postgres_prod_data:
  postgres_test_data:
