spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5434/${DB_PROD}
    username: ${POSTGRES_USER_PROD}
    password: ${PASSWORD_DB_PROD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
    - classpath:db/migration/prod
    