spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
    - classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
api:
  token:
    security: ${API_TOKEN_SECRET} 
logging:
  level:
    '[org.flywaydb]': info
  
