spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_DEV}
    username: ${POSTGRES_USER_DEV}
    password: ${PASSWORD_DB_DEV}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/dev  
    baseline-on-migrate: true  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    '[org.flywaydb]': debug   
