spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5435/test
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
    - classpath:db/migration
    baseline-on-migrate: true  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
api:
  token:
    security: ${API_TOKEN_SECRET} 
logging:
  level:
    '[org.flywaydb]': debug 
    