spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5435/forohub_test
    username: ${USERNAME_DB_TEST}
    password: ${PASSWORD_DB_TEST}
    driver-class-name: org.postgresql.Driver