spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER_PROD}
    password: ${PASSWORD_DB_PROD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
    - classpath:db/migration/prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  token:
    security: ${API_TOKEN_SECRET} 
logging:
  level:
    '[org.flywaydb]': info
